### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by TimoSalomaki** [Limeoats/L2DFileDialog#1]
First of all, great work with the library! I'm just adding a listing of it to my [Awesome Dear Imgui](https://github.com/HankiDesign/awesome-dear-imgui) list and noticed that your license file is missing from the repo. I'll list it as Apache License as you've written in the readme.md file but let me know if that has changed.

**Comment by Limeoats** [comment]
Thanks for the heads up. Fixed in 4c4d09bf4743f5e73a481d0d2c1be017b9d99794

**Comment by Limeoats** [comment]
and 032092f5a21bed4ae58f003a5c5356f8acbdac71
