### ISSUE TITLE
No filepath support

### ISSUE THREAD

**Issue by goodle06** [Limeoats/L2DFileDialog#2]
Hi!

It seems to me that project doesn't have filepath support, only folder support. Please see this code snippet:

`
if (ImGui::Button("Choose")) {

				if (**type == FileDialogType::SelectFolder**) {
					if (fileDialogCurrentFolder == "") {
						strcpy_s(fileDialogError, "Error: You must select a folder!");
					}
					else {
						strcpy(buffer, (fileDialogCurrentPath + (fileDialogCurrentPath.back() == '\\' ? "" : "\\") + fileDialogCurrentFolder).c_str());
						fileDialogFileSelectIndex = 0;
						fileDialogFolderSelectIndex = 0;
						fileDialogCurrentFile = "";
						fileDialogOpen = false;
					}
				}
			}`

You don't have type FileDialogType::OpenFile. I've made nessessary modifications, if you're willing I would like to share.

**Comment by Limeoats** [comment]
Hi @goodle06 ,

Sure! I created this with the intention of using it for selecting folders, but I'd be willing to add file chooser support. Please open a pull request with your changes and I'll take a look.

Thanks!

**Comment by goodle06** [comment]
Hi again, @Limeoats , please checkout pull request.

**Comment by Limeoats** [comment]
Added this in 4ed4134e19f25acb9d1f6a7e29b031f127969ef5, along with a bunch of other enhancements.
