### ISSUE TITLE
use of undeclared identifier 'strcpy_s'

### ISSUE THREAD

**Issue by mumin16** [Limeoats/L2DFileDialog#7]
i have error " use of undeclared identifier 'strcpy_s' "

**Comment by AbduEhab** [comment]
If I may ask what compiler and platform are you using?

It may be that you're using an earlier version of the c++ standard. Try using C++17 or later.

**Comment by Limeoats** [comment]
As mentioned above, make sure you're using C++17 or later. Things like `std::filesystem` and `strcpy_s` are from C++17 and you won't be able to compile unless you're using that version or later.
